name: qdamono_fluent
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  flutter_riverpod: ^2.3.7
  riverpod_annotation: ^2.1.2
  fluent_ui: ^4.7.3
  fluentui_icons: ^1.0.0
  go_router: ^10.1.0
  multi_split_view: ^2.4.0
  window_manager: ^0.3.5
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  collection: ^1.17.2
  shared_preferences: ^2.2.0
  system_theme: ^2.3.1
  http: ^1.1.0
  uuid: ^3.0.7
  markdown: ^7.1.1
  flutter_markdown_selectionarea: ^0.6.17+1
  intl: ^0.18.1
  
# Use forks uploaded to GitHub when they are ready
dependency_overrides:
  flutter:
    git: https://github.com/qdamono/flutter-qdamono-fork.git
  fluent_ui:
    git: https://github.com/qdamono/fluent_ui-qdamono-fork.git

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  custom_lint: ^0.5.2
  riverpod_lint: ^2.0.1
  build_runner: ^2.4.6
  riverpod_generator: ^2.2.6
  freezed: ^2.4.2
  json_serializable: ^6.7.1
  intl_utils: ^2.8.5

flutter:
  uses-material-design: true
